#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006-2013
#

USAGE="[-f] <patchname>..."
if [ -z "$GUILT_VERSION" ]; then
	echo "Invoking `basename "$0"` directly is no longer supported." >&2
	exit 1
fi

_main() {

force=false
if [ "$1" = "-f" ]; then
	shift
	force=true
fi

if [ $# -eq 0 ]; then
	usage
fi

# check patches passed
for patch in "$@"; do
	if [ ! -f "$GUILT_DIR/$branch/$patch" ]; then
		die "Patch $patch does not exist."
	fi

	p=`grep -x -e "$patch" < "$applied"`
	if [ ! -z "$p" ] ; then
		die "Cannot delete an applied patch"
	fi
done

# do the real job
for patch in "$@"; do
	series_remove_patch "$patch"

	guilt_hook "delete" "$patch"

	$force && rm -f "$GUILT_DIR/$branch/$patch"
done

exit 0

}
